### ISSUE TITLE
Возможность использования поля с типом "Date and time"

### ISSUE THREAD

**Issue by DmitriyKhlopin** [olegbakhirev/due-dates-calendar-widget#7]
Добрый день.
Возможность использования поля с типом "Date and time" была бы очень полезной, т.к. существуют сценарии, в которых могут использоваться даты только со временем. Пример - время ответов по SLA - в этом случае и время должно быть указано, и виджет мог бы сильно помочь с визуализацией таких запросов.
Реализуйте, пожалуйста, при наличии возможности.

**Comment by AnianZ** [comment]
_Translation Service:_
Good day.
The possibility of using the field with the type "Date and time" would be very useful, because There are scenarios in which dates can only be used over time. An example is the time of SLA responses — in this case, the time must also be specified, and the widget could greatly help with the visualization of such requests.
Please implement if possible.

I ran into the same issue

**Comment by olegbakhirev** [comment]
Fixed this. Version 1.3 of the widget in widget repository supports selecting this fields and enables calendar time tables
